# Podfile for EroticLiveX iOS App
platform :ios, '14.0'

target 'EroticLiveX' do
  use_frameworks!
  
  # Firebase Cloud Messaging & Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  
  # Networking & Async
  pod 'Alamofire'
  
  # UI & Image Loading
  pod 'SDWebImage'
  
  # Development Dependencies
  target 'EroticLiveXTests' do
    inherit! :search_paths
  end
  
  target 'EroticLiveXUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'FIREBASE_ANALYTICS_COLLECTION_ENABLED=1'
      ]
    end
  end
end
